//! GM Detector — zone-wide Game Master detection and alerting.
//!
//! Detects when a Game Master enters the zone (unless in stealth mode) and
//! provides immediate alerts for all connected clients. Parity with MQ2GMCheck.
//!
//! # Features
//!
//! - GM spawn detection within one game pulse (< 1 second)
//! - Broadcast alerts to all connected clients immediately
//! - Sound alert + TUI notification support
//! - Optional automation auto-pause when GM is in zone
//! - Automation resumes after GM leaves zone
//!
//! # Usage
//!
//! ```
//! use textquest::eq::gm_detector::{GmDetector, GmAlertConfig};
//!
//! let mut detector = GmDetector::new(GmAlertConfig::default());
//! detector.update_spawns(&spawns);
//!
//! for event in detector.pending_events() {
//!     // Handle GM_ENTERED or GM_DEPARTED events
//! }
//! ```

use std::collections::{HashMap, HashSet, VecDeque};
use std::time::SystemTime;

use serde::{Deserialize, Serialize};

use crate::eq::structs::SpawnInfo;

/// Configuration for GM alerts.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GmAlertConfig {
    /// Enable GM detection and alerts.
    pub enabled: bool,
    /// Play a sound alert when GM detected.
    pub sound_enabled: bool,
    /// Sound file to play (relative to config/sounds).
    pub sound_file: Option<String>,
    /// Show TUI toast notification.
    pub toast_enabled: bool,
    /// Auto-pause automation when GM is in zone.
    pub auto_pause_enabled: bool,
    /// Discord webhook URL for GM alerts.
    pub discord_webhook_url: Option<String>,
    /// Broadcast to all connected clients.
    pub broadcast_all_clients: bool,
}

impl Default for GmAlertConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            sound_enabled: true,
            sound_file: Some("gm_alert.wav".to_string()),
            toast_enabled: true,
            auto_pause_enabled: false,
            discord_webhook_url: None,
            broadcast_all_clients: true,
        }
    }
}

/// A GM alert event generated by the detector.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GmAlertEvent {
    /// Type of GM event.
    pub event_type: GmEventType,
    /// Name of the GM spawn.
    pub gm_name: String,
    /// Zone where the event occurred.
    pub zone: String,
    /// Spawn ID of the GM.
    pub spawn_id: u32,
    /// Level of the GM.
    pub level: u8,
    /// When the event occurred.
    pub timestamp: SystemTime,
}

/// Type of GM event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GmEventType {
    /// GM has entered the zone.
    GmEntered,
    /// GM has left the zone.
    GmDeparted,
}

impl GmEventType {
    /// Human-readable label for the event type.
    #[must_use]
    pub fn label(&self) -> &'static str {
        match self {
            Self::GmEntered => "GM Entered Zone",
            Self::GmDeparted => "GM Left Zone",
        }
    }
}

/// State of GM presence in a zone.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GmPresenceState {
    /// No GM in zone.
    Clear,
    /// GM detected in zone.
    GmPresent,
}

/// Current GM presence status.
#[derive(Debug, Clone)]
pub struct GmPresence {
    /// Current presence state.
    pub state: GmPresenceState,
    /// Names of GMs currently in zone.
    pub gm_names: Vec<String>,
    /// Count of GMs in zone.
    pub gm_count: usize,
    /// Timestamp when last GM event occurred.
    pub last_event: Option<SystemTime>,
}

impl GmPresence {
    /// Returns true if any GM is currently in zone.
    #[must_use]
    pub fn is_gm_in_zone(&self) -> bool {
        self.state == GmPresenceState::GmPresent
    }
}

impl Default for GmPresence {
    fn default() -> Self {
        Self {
            state: GmPresenceState::Clear,
            gm_names: Vec::new(),
            gm_count: 0,
            last_event: None,
        }
    }
}

/// GM Detector — tracks Game Masters entering and leaving zones.
///
/// Monitors spawn lists and generates immediate alerts when GMs are detected.
pub struct GmDetector {
    config: GmAlertConfig,
    events: VecDeque<GmAlertEvent>,
    known_gms: HashMap<u32, String>,
    presence: GmPresence,
}

impl Default for GmDetector {
    fn default() -> Self {
        Self::new(GmAlertConfig::default())
    }
}

impl GmDetector {
    /// Create a new GM detector with the given configuration.
    #[must_use]
    pub fn new(config: GmAlertConfig) -> Self {
        Self {
            config,
            events: VecDeque::new(),
            known_gms: HashMap::new(),
            presence: GmPresence::default(),
        }
    }

    /// Update configuration.
    pub fn set_config(&mut self, config: GmAlertConfig) {
        self.config = config;
    }

    /// Get current configuration reference.
    #[must_use]
    pub fn config(&self) -> &GmAlertConfig {
        &self.config
    }

    /// Get current GM presence status.
    #[must_use]
    pub fn presence(&self) -> &GmPresence {
        &self.presence
    }

    /// Returns true if GM detection is enabled.
    #[must_use]
    pub fn is_enabled(&self) -> bool {
        self.config.enabled
    }

    /// Returns true if any GM is currently in zone.
    #[must_use]
    pub fn is_gm_in_zone(&self) -> bool {
        self.presence.is_gm_in_zone()
    }

    /// Update detector with current spawn list.
    ///
    /// Call this each game pulse/tick with the current zone spawn list.
    /// Generates events for any GM state changes.
    pub fn update_spawns(&mut self, spawns: &[SpawnInfo], zone: &str) {
        if !self.config.enabled {
            return;
        }

        let mut current_gm_ids: HashSet<u32> = HashSet::new();

        for spawn in spawns {
            if spawn.is_gm && spawn.spawn_type == crate::eq::structs::SpawnType::Player {
                current_gm_ids.insert(spawn.spawn_id);

                let is_new = self
                    .known_gms
                    .insert(spawn.spawn_id, spawn.name.clone())
                    .is_none();

                if is_new {
                    let event = GmAlertEvent {
                        event_type: GmEventType::GmEntered,
                        gm_name: spawn.name.clone(),
                        zone: zone.to_string(),
                        spawn_id: spawn.spawn_id,
                        level: spawn.level,
                        timestamp: SystemTime::now(),
                    };
                    tracing::info!(
                        gm_name = %spawn.name,
                        zone = %zone,
                        spawn_id = spawn.spawn_id,
                        "GM detected entering zone"
                    );
                    self.events.push_back(event);
                }
            }
        }

        let departed_gms: Vec<(u32, String)> = self
            .known_gms
            .iter()
            .filter(|(id, _)| !current_gm_ids.contains(id))
            .map(|(id, name)| (*id, name.clone()))
            .collect();

        for (spawn_id, name) in departed_gms {
            self.known_gms.remove(&spawn_id);

            let event = GmAlertEvent {
                event_type: GmEventType::GmDeparted,
                gm_name: name,
                zone: zone.to_string(),
                spawn_id,
                level: 0,
                timestamp: SystemTime::now(),
            };
            tracing::info!(
                spawn_id = spawn_id,
                zone = %zone,
                "GM departed zone"
            );
            self.events.push_back(event);
        }

        self.update_presence(zone);
    }

    fn update_presence(&mut self, zone: &str) {
        if self.known_gms.is_empty() {
            if self.presence.state != GmPresenceState::Clear {
                tracing::debug!(zone = %zone, "Zone cleared of GMs");
            }
            self.presence = GmPresence {
                state: GmPresenceState::Clear,
                gm_names: Vec::new(),
                gm_count: 0,
                last_event: Some(SystemTime::now()),
            };
        } else {
            let gm_names: Vec<String> = self.known_gms.values().cloned().collect();
            if self.presence.state != GmPresenceState::GmPresent {
                tracing::warn!(zone = %zone, gm_count = gm_names.len(), "GM present in zone");
            }
            self.presence = GmPresence {
                state: GmPresenceState::GmPresent,
                gm_names,
                gm_count: self.known_gms.len(),
                last_event: Some(SystemTime::now()),
            };
        }
    }

    /// Drain and return all pending GM alert events.
    ///
    /// Events are removed from the queue when returned.
    #[must_use]
    pub fn pending_events(&mut self) -> Vec<GmAlertEvent> {
        let events: Vec<_> = self.events.drain(..).collect();
        events
    }

    /// Peek at pending events without consuming them.
    pub fn peek_events(&self) -> impl Iterator<Item = &GmAlertEvent> {
        self.events.iter()
    }

    /// Number of pending events.
    #[must_use]
    pub fn pending_count(&self) -> usize {
        self.events.len()
    }

    /// Clear all tracked GMs and reset state.
    pub fn reset(&mut self) {
        self.known_gms.clear();
        self.events.clear();
        self.presence = GmPresence::default();
    }

    /// Should automation be paused based on current state?
    #[must_use]
    pub fn should_pause_automation(&self) -> bool {
        self.config.enabled
            && self.config.auto_pause_enabled
            && self.presence.state == GmPresenceState::GmPresent
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::eq::structs::{SpawnInfo, SpawnType};

    fn make_gm_spawn(id: u32, name: &str, level: u8) -> SpawnInfo {
        SpawnInfo {
            name: name.to_string(),
            displayed_name: name.to_string(),
            lastname: String::new(),
            spawn_id: id,
            spawn_type: SpawnType::Player,
            level,
            class_id: 1,
            class: None,
            stand_state: crate::eq::structs::StandState::Standing,
            x: 0.0,
            y: 0.0,
            z: 0.0,
            heading: 0.0,
            hp_current: 1000,
            hp_max: 1000,
            mana_current: 500,
            mana_max: 500,
            endurance_current: 100,
            endurance_max: 100,
            is_gm: true,
            race_id: 1,
            buff_slots: Vec::new(),
            spellbook: Vec::new(),
            memorized_spells: Vec::new(),
            cast_state: None,
        }
    }

    fn make_pc_spawn(id: u32, name: &str) -> SpawnInfo {
        SpawnInfo {
            name: name.to_string(),
            displayed_name: name.to_string(),
            lastname: String::new(),
            spawn_id: id,
            spawn_type: SpawnType::Player,
            level: 60,
            class_id: 1,
            class: None,
            stand_state: crate::eq::structs::StandState::Standing,
            x: 0.0,
            y: 0.0,
            z: 0.0,
            heading: 0.0,
            hp_current: 1000,
            hp_max: 1000,
            mana_current: 500,
            mana_max: 500,
            endurance_current: 100,
            endurance_max: 100,
            is_gm: false,
            race_id: 1,
            buff_slots: Vec::new(),
            spellbook: Vec::new(),
            memorized_spells: Vec::new(),
            cast_state: None,
        }
    }

    #[test]
    fn no_events_when_disabled() {
        let config = GmAlertConfig {
            enabled: false,
            ..GmAlertConfig::default()
        };
        let mut detector = GmDetector::new(config);

        let spawns = vec![make_gm_spawn(1, "TestGM", 65)];
        detector.update_spawns(&spawns, "test_zone");

        assert!(detector.pending_events().is_empty());
    }

    #[test]
    fn detects_gm_enter() {
        let mut detector = GmDetector::new(GmAlertConfig::default());

        let spawns = vec![make_gm_spawn(1, "TestGM", 65)];
        detector.update_spawns(&spawns, "test_zone");

        let events = detector.pending_events();
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].event_type, GmEventType::GmEntered);
        assert_eq!(events[0].gm_name, "TestGM");
        assert!(detector.is_gm_in_zone());
    }

    #[test]
    fn detects_gm_depart() {
        let mut detector = GmDetector::new(GmAlertConfig::default());

        let initial_spawns = vec![make_gm_spawn(1, "TestGM", 65)];
        detector.update_spawns(&initial_spawns, "test_zone");
        assert!(detector.pending_events().len() == 1);

        let empty_spawns: Vec<SpawnInfo> = vec![];
        detector.update_spawns(&empty_spawns, "test_zone");

        let events = detector.pending_events();
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].event_type, GmEventType::GmDeparted);
        assert!(!detector.is_gm_in_zone());
    }

    #[test]
    fn no_event_for_non_gm_spawns() {
        let mut detector = GmDetector::new(GmAlertConfig::default());

        let spawns = vec![
            make_pc_spawn(1, "RegularPlayer1"),
            make_pc_spawn(2, "RegularPlayer2"),
        ];
        detector.update_spawns(&spawns, "test_zone");

        assert!(detector.pending_events().is_empty());
        assert!(!detector.is_gm_in_zone());
    }

    #[test]
    fn handles_multiple_gms() {
        let mut detector = GmDetector::new(GmAlertConfig::default());

        let spawns = vec![
            make_gm_spawn(1, "GM_One", 65),
            make_gm_spawn(2, "GM_Two", 70),
        ];
        detector.update_spawns(&spawns, "test_zone");

        let events = detector.pending_events();
        assert_eq!(events.len(), 2);

        let presence = detector.presence();
        assert_eq!(presence.gm_count, 2);
        assert!(presence.gm_names.contains(&"GM_One".to_string()));
        assert!(presence.gm_names.contains(&"GM_Two".to_string()));
    }

    #[test]
    fn presence_updates_correctly() {
        let mut detector = GmDetector::new(GmAlertConfig::default());

        assert_eq!(detector.presence().state, GmPresenceState::Clear);

        let spawns = vec![make_gm_spawn(1, "TestGM", 65)];
        detector.update_spawns(&spawns, "test_zone");
        assert_eq!(detector.presence().state, GmPresenceState::GmPresent);

        let empty: Vec<SpawnInfo> = vec![];
        detector.update_spawns(&empty, "test_zone");
        assert_eq!(detector.presence().state, GmPresenceState::Clear);
    }

    #[test]
    fn should_pause_automation() {
        let mut detector = GmDetector::new(GmAlertConfig {
            auto_pause_enabled: true,
            ..GmAlertConfig::default()
        });

        assert!(!detector.should_pause_automation());

        let spawns = vec![make_gm_spawn(1, "TestGM", 65)];
        detector.update_spawns(&spawns, "test_zone");

        assert!(detector.should_pause_automation());
    }

    #[test]
    fn should_not_pause_when_disabled() {
        let mut detector = GmDetector::new(GmAlertConfig {
            enabled: false,
            auto_pause_enabled: true,
            ..GmAlertConfig::default()
        });

        let spawns = vec![make_gm_spawn(1, "TestGM", 65)];
        detector.update_spawns(&spawns, "test_zone");

        assert!(!detector.should_pause_automation());
    }

    #[test]
    fn should_not_pause_when_auto_pause_disabled() {
        let mut detector = GmDetector::new(GmAlertConfig {
            auto_pause_enabled: false,
            ..GmAlertConfig::default()
        });

        let spawns = vec![make_gm_spawn(1, "TestGM", 65)];
        detector.update_spawns(&spawns, "test_zone");

        assert!(!detector.should_pause_automation());
    }

    #[test]
    fn reset_clears_all_state() {
        let mut detector = GmDetector::new(GmAlertConfig::default());

        let spawns = vec![make_gm_spawn(1, "TestGM", 65)];
        detector.update_spawns(&spawns, "test_zone");
        assert!(detector.is_gm_in_zone());

        detector.reset();

        assert!(!detector.is_gm_in_zone());
        assert!(detector.pending_events().is_empty());
    }

    #[test]
    fn default_config_values() {
        let config = GmAlertConfig::default();
        assert!(config.enabled);
        assert!(config.sound_enabled);
        assert!(config.toast_enabled);
        assert!(!config.auto_pause_enabled);
        assert!(config.broadcast_all_clients);
    }

    #[test]
    fn gm_event_type_labels() {
        assert_eq!(GmEventType::GmEntered.label(), "GM Entered Zone");
        assert_eq!(GmEventType::GmDeparted.label(), "GM Left Zone");
    }

    #[test]
    fn peek_does_not_consume_events() {
        let mut detector = GmDetector::new(GmAlertConfig::default());

        let spawns = vec![make_gm_spawn(1, "TestGM", 65)];
        detector.update_spawns(&spawns, "test_zone");

        assert_eq!(detector.pending_count(), 1);
        assert_eq!(detector.peek_events().count(), 1);
        assert_eq!(detector.pending_count(), 1);

        let events = detector.pending_events();
        assert_eq!(events.len(), 1);
        assert_eq!(detector.pending_count(), 0);
    }
}
