use std::collections::HashMap;
use std::path::Path;
use std::time::{Duration, Instant};

use anyhow::Result;
use textquest_common::ipc::Command;
use textquest_common::soul::{MoodState, PersonalityTraits, SoulAction, SoulEvent, SpeechStyle};
use textquest_common::types::{ClientId, GameState};

use super::alerts::{Alert, AnomalyDetector};
use super::config::{CharacterSoulConfig, EdginessLevel, SoulConfig};
use super::idle::{IdleScheduler, IdleTransition};
use super::llm::fallback::TraitDrivenResponder;
use super::llm::priority_queue::LlmRequestQueue;
use super::llm::{LlmPriority, LlmProvider, LlmRequest, Situation};
use super::memory::MemoryStore;
use super::personality::{PersonalityEngine, SoulContext};
use super::social::SocialGraph;

use super::audit::{AuditActionType, SoulAuditLogger};

// ── Alert system ─────────────────────────────────────────────────────────────

/// Classification of what triggered an alert.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum AlertType {
    /// Character mood has not changed for longer than the configured threshold.
    MoodStuck,
    /// Character is generating chat messages faster than the configured threshold.
    ChatSpam,
    /// The memory table for a character is near its capacity limit.
    MemoryFull,
    /// The LLM provider has been unavailable for longer than the configured threshold.
    ProviderError,
    /// Character behavior is inconsistent with its configured personality traits.
    UnexpectedBehavior,
}

/// How urgent an alert is.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum AlertSeverity {
    Info,
    Warning,
    Error,
    Critical,
}

/// An operator alert generated by the Soul Engine coordinator.
#[derive(Debug, Clone)]
pub struct Alert {
    /// The character that triggered the alert (0 = coordinator-wide).
    pub character_id: ClientId,
    /// What kind of anomaly was detected.
    pub alert_type: AlertType,
    /// How urgent the alert is.
    pub severity: AlertSeverity,
    /// Human-readable description of the anomaly.
    pub message: String,
    /// Wall-clock time the alert was generated.
    pub timestamp: Instant,
    /// Whether the operator has acknowledged (dismissed) this alert.
    pub acknowledged: bool,
    /// Whether the operator has marked this as a false alarm.
    pub false_alarm: bool,
}

impl Alert {
    fn new(
        character_id: ClientId,
        alert_type: AlertType,
        severity: AlertSeverity,
        message: impl Into<String>,
    ) -> Self {
        Self {
            character_id,
            alert_type,
            severity,
            message: message.into(),
            timestamp: Instant::now(),
            acknowledged: false,
            false_alarm: false,
        }
    }
}

/// Configuration for alert thresholds.
#[derive(Debug, Clone)]
pub struct AlertConfig {
    /// Hours a mood must remain unchanged before a `MoodStuck` alert fires.
    pub mood_stuck_hours: u64,
    /// Max messages per minute before a `ChatSpam` alert fires.
    pub chat_spam_threshold: u32,
    /// Memory table fill percentage (0–100) before a `MemoryFull` alert fires.
    pub memory_full_percent: u8,
    /// Minutes the LLM provider must be unavailable before a `ProviderError` alert fires.
    pub provider_timeout_minutes: u64,
    /// Minimum seconds between duplicate alerts of the same type for the same character.
    pub dedup_secs: u64,
}

impl Default for AlertConfig {
    fn default() -> Self {
        Self {
            mood_stuck_hours: 2,
            chat_spam_threshold: 5,
            memory_full_percent: 90,
            provider_timeout_minutes: 30,
            dedup_secs: 300,
        }
    }
}

// ── Per-character alert tracking state ───────────────────────────────────────

/// Per-character state used for alert detection.
struct AlertState {
    /// When the current mood was first observed.
    mood_since: Instant,
    /// The mood value recorded at `mood_since`.
    last_mood: MoodState,
    /// Timestamps of recent outbound chat messages (used for spam detection).
    recent_chat_times: Vec<Instant>,
    /// Per alert-type last-fired times (for deduplication).
    last_fired: HashMap<AlertType, Instant>,
}

/// Per-character soul state.
struct CharacterSoul {
    name: String,
    client_id: ClientId,
    traits: PersonalityTraits,
    mood: MoodState,
    speech_style: SpeechStyle,
    edginess: EdginessLevel,
    backstory: String,
    personality: PersonalityEngine,
    idle: IdleScheduler,
    responder: TraitDrivenResponder,
    /// Alert detection tracking for this character.
    alert_state: AlertState,
}

/// Tick-driven orchestrator for all Soul Engine subsystems.
/// Mirrors `CombatCoordinator`: called each tick, returns commands to dispatch.
pub struct SoulCoordinator {
    souls: HashMap<ClientId, CharacterSoul>,
    memory: MemoryStore,
    social: SocialGraph,
    llm_queue: LlmRequestQueue,
    config: SoulConfig,
    /// Tick counter for timing.
    tick_count: u64,
    /// Pending alerts waiting to be drained by the operator.
    pending_alerts: Vec<Alert>,
    /// Alert threshold configuration.
    alert_config: AlertConfig,
    /// Optional audit logger — `None` when no log path was provided.
    audit: Option<SoulAuditLogger>,
}

const MAX_PLAYER_CHAT_MESSAGE_BYTES: usize = 512;
const MAX_CONVERSATIONS_PER_CHARACTER: usize = 1000;

impl SoulCoordinator {
    /// Create a new `SoulCoordinator` from config.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    pub fn new(config: SoulConfig, db_path: &Path) -> Result<Self> {
        let memory = MemoryStore::open(db_path)?;
        let social = SocialGraph::from_seeds(&config.relationship);
        // Phase 1: 0 token budget (fallback only, no real LLM calls)
        let llm_queue = LlmRequestQueue::new(0);

        Ok(Self {
            souls: HashMap::new(),
            memory,
            social,
            llm_queue,
            config,
            tick_count: 0,
            pending_alerts: Vec::new(),
            alert_config: AlertConfig::default(),
            audit: None,
        })
    }

    /// Attach a `SoulAuditLogger` to this coordinator.
    ///
    /// Once set, key state changes (mood, memory, LLM requests, events) are
    /// written as JSONL lines to the logger's file.
    pub fn set_audit_logger(&mut self, logger: SoulAuditLogger) {
        self.audit = Some(logger);
    }

    /// Register a character with the coordinator.
    pub fn register_character(&mut self, client_id: ClientId, char_config: &CharacterSoulConfig) {
        let edginess = char_config.edginess.unwrap_or(self.config.edginess);

        let soul = CharacterSoul {
            name: char_config.name.clone(),
            client_id,
            traits: char_config.traits.clone(),
            mood: MoodState::Neutral,
            speech_style: char_config.speech.clone(),
            edginess,
            backstory: char_config.backstory.clone(),
            personality: PersonalityEngine::new(client_id),
            idle: IdleScheduler::new(client_id, &self.config),
            responder: TraitDrivenResponder::new(client_id, edginess),
            alert_state: AlertState {
                mood_since: Instant::now(),
                last_mood: MoodState::Neutral,
                recent_chat_times: Vec::new(),
                last_fired: HashMap::new(),
            },
        };

        self.souls.insert(client_id, soul);
        self.anomaly_detector.register_character(client_id);
    }

    /// Main tick — called every 5000ms by the orchestrator.
    /// Returns `(commands, alerts)` so the caller can dispatch commands and act on anomalies.
    pub fn tick(
        &mut self,
        states: &HashMap<ClientId, GameState>,
    ) -> (Vec<(ClientId, Command)>, Vec<Alert>) {
        if !self.config.enabled {
            return (Vec::new(), Vec::new());
        }

        self.tick_count += 1;
        let mut commands = Vec::new();

        // Collect client IDs to avoid borrow issues
        let client_ids: Vec<ClientId> = self.souls.keys().copied().collect();

        for client_id in client_ids {
            let Some(soul) = self.souls.get_mut(&client_id) else {
                continue;
            };

            let Some(state) = states.get(&client_id) else {
                continue;
            };

            let in_combat = is_in_combat(state);
            let zone = zone_from_state(state);
            // Approximate group members from nearby PCs (spawn_type 0 = player).
            // True group roster requires GameState to carry group membership data.
            let group_members: Vec<String> = state
                .nearby_spawns
                .iter()
                .filter(|s| s.spawn_type == 0 && s.name != soul.name)
                .map(|s| s.name.clone())
                .collect();

            let ctx = SoulContext {
                character_name: &soul.name,
                traits: &soul.traits,
                mood: soul.mood,
                edginess: soul.edginess,
                zone,
                level: state.local_player.as_ref().map_or(1, |p| p.level),
                in_combat,
                group_members: &group_members,
            };

            // Tick idle scheduler
            match soul.idle.tick(&ctx, &mut soul.responder) {
                IdleTransition::Start(active) => {
                    // Convert idle behavior to a Command
                    let action = SoulAction::StartIdle {
                        behavior: active.behavior.clone(),
                    };
                    commands.push((client_id, Command::SoulAction { action }));

                    // If there's flavor text, emit it as chat
                    if let Some(text) = active.flavor_text {
                        commands.push((
                            client_id,
                            Command::Say {
                                channel: textquest_common::soul::SayChannel::Group,
                                message: text,
                                target: None,
                            },
                        ));
                    }
                }
                IdleTransition::LogOff { return_after_secs } => {
                    tracing::info!(
                        client_id,
                        name = soul.name,
                        return_after_secs,
                        "Character logging off to sleep"
                    );
                    let action = SoulAction::StartIdle {
                        behavior: textquest_common::soul::IdleBehaviorType::LogOffToSleep,
                    };
                    commands.push((client_id, Command::SoulAction { action }));
                }
                IdleTransition::Stop | IdleTransition::Continue => {}
            }

            // Periodic memory decay (every ~60 ticks = 5 minutes at 5s tick)
            if self.tick_count.is_multiple_of(60) {
                let _ = self.memory.decay_tick(client_id, 0.995);
                let _ = self.memory.prune_low_importance(client_id, 0.05);
            }

            // Alert detection — runs every tick, lightweight checks only.
            self.check_alerts_for(client_id);
        }

        // Process any queued LLM requests
        let now_secs = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_or(0, |d| d.as_secs());

        // Drain all ready requests, then process each with the matching soul's responder
        // In Phase 2, this will use a real LLM provider instead of per-soul fallback responders
        let pending: Vec<_> = {
            let mut results = Vec::new();
            while let Some(prioritized) = self.llm_queue.pop_next(now_secs) {
                results.push(prioritized);
            }
            results
        };

        for request in pending {
            if let Some((&cid, soul)) = self
                .souls
                .iter_mut()
                .find(|(_, s)| s.name == request.character_name)
                && let Ok(response) = soul.responder.generate(&request)
            {
                commands.push((
                    cid,
                    Command::Say {
                        channel: textquest_common::soul::SayChannel::Say,
                        message: response.text,
                        target: None,
                    },
                ));
            }
        }

        // Track outbound chat messages for spam detection.
        // We do this after the full command list is built so we can scan it once.
        let chat_senders: Vec<ClientId> = commands
            .iter()
            .filter_map(|(cid, cmd)| {
                if matches!(cmd, Command::Say { .. }) {
                    Some(*cid)
                } else {
                    None
                }
            })
            .collect();
        for cid in chat_senders {
            self.record_chat_sent(cid);
        }

        commands
    }

    /// Handle an incoming message from a real player.
    pub fn on_player_message(
        &mut self,
        client_id: ClientId,
        player_name: &str,
        message: &str,
        channel: &str,
    ) {
        if !self.config.player_chat_enabled {
            return;
        }

        let Some(soul) = self.souls.get_mut(&client_id) else {
            return;
        };

        let message = message.trim();
        if message.is_empty() {
            return;
        }
        let message = truncate_utf8(message, MAX_PLAYER_CHAT_MESSAGE_BYTES);

        // Record the conversation
        let _ =
            self.memory
                .record_conversation(client_id, player_name, true, channel, message, 0.0);
        let _ = self
            .memory
            .prune_conversations(client_id, MAX_CONVERSATIONS_PER_CHARACTER);

        // Capture mood before event processing for accurate memory recording
        let mood_before = soul.mood;

        // Process mood change from player interaction
        let event = SoulEvent::PlayerChat {
            player_name: player_name.to_string(),
            sentiment: 0.0, // Neutral default; LLM-based sentiment analysis deferred to M6
        };
        soul.mood = soul
            .personality
            .process_event(soul.mood, &event, &soul.traits);

        if let Some(audit) = &self.audit
            && mood_before != soul.mood
        {
            let _ = audit.log(
                client_id,
                AuditActionType::MoodChange,
                format!(
                    "{} mood: {:?} -> {:?} (player chat from {})",
                    soul.name, mood_before, soul.mood, player_name
                ),
                Some(serde_json::json!({"mood": format!("{:?}", mood_before)})),
                Some(serde_json::json!({"mood": format!("{:?}", soul.mood)})),
            );
        }

        // Record memory with the mood as it was before the event changed it
        let _ = self.memory.record(client_id, &event, mood_before, 2.0);

        // Audit: memory record
        if let Some(audit) = &self.audit {
            let _ = audit.log(
                client_id,
                AuditActionType::MemoryRecord,
                format!(
                    "{} recorded player chat memory from {}",
                    soul.name, player_name
                ),
                None,
                None,
            );
        }

        // Queue an LLM response (high priority for real players)
        let request = LlmRequest {
            character_name: soul.name.clone(),
            traits: soul.traits.clone(),
            mood: soul.mood,
            speech_style: soul.speech_style.clone(),
            situation: Situation::PlayerChat {
                player_name: player_name.to_string(),
                message: message.to_owned(),
                channel: channel.to_string(),
            },
            priority: LlmPriority::High,
            memory_context: self
                .memory
                .recall_about(client_id, player_name, 5)
                .unwrap_or_default()
                .into_iter()
                .map(|row| row.event_json)
                .collect(),
            backstory: soul.backstory.clone(),
        };

        // Audit: LLM request enqueued
        if let Some(audit) = &self.audit {
            let _ = audit.log(
                client_id,
                AuditActionType::LlmRequest,
                format!(
                    "{} LLM request enqueued for player chat from {}",
                    soul.name, player_name
                ),
                None,
                Some(serde_json::json!({"priority": "High", "channel": channel})),
            );
        }

        self.llm_queue.enqueue(request);
    }

    /// Handle a game event (kill, death, loot, zone change, etc.).
    pub fn on_game_event(&mut self, client_id: ClientId, event: SoulEvent) {
        // Notify the anomaly detector that a soul event was received.
        self.anomaly_detector.record_soul_event(client_id);

        let Some(soul) = self.souls.get_mut(&client_id) else {
            return;
        };

        // Capture mood before event processing for accurate memory recording
        let mood_before = soul.mood;

        // Update mood
        soul.mood = soul
            .personality
            .process_event(soul.mood, &event, &soul.traits);

        // Audit: event processed
        if let Some(audit) = &self.audit {
            let _ = audit.log(
                client_id,
                AuditActionType::EventProcessed,
                format!("{} processed game event: {:?}", soul.name, event),
                Some(serde_json::json!({"mood": format!("{:?}", mood_before)})),
                Some(serde_json::json!({"mood": format!("{:?}", soul.mood)})),
            );
        }

        if let Some(audit) = &self.audit
            && mood_before != soul.mood
        {
            let _ = audit.log(
                client_id,
                AuditActionType::MoodChange,
                format!(
                    "{} mood: {:?} -> {:?} (game event)",
                    soul.name, mood_before, soul.mood
                ),
                Some(serde_json::json!({"mood": format!("{:?}", mood_before)})),
                Some(serde_json::json!({"mood": format!("{:?}", soul.mood)})),
            );
        }

        // Determine importance based on event type
        let importance = match &event {
            SoulEvent::Death { .. } | SoulEvent::GroupWipe { .. } => 5.0,
            SoulEvent::LevelUp { .. } => 4.0,
            SoulEvent::Kill { .. } | SoulEvent::Loot { .. } => 1.5,
            SoulEvent::PlayerChat { .. } => 3.0,
            SoulEvent::RelationshipChange { .. } => 2.0,
            SoulEvent::ZoneEnter { .. } => 1.0,
            _ => 1.0,
        };

        // Record memory with the mood as it was before the event changed it
        let _ = self
            .memory
            .record(client_id, &event, mood_before, importance);

        // Audit: memory record
        if let Some(audit) = &self.audit {
            let _ = audit.log(
                client_id,
                AuditActionType::MemoryRecord,
                format!(
                    "{} recorded game event memory (importance {importance})",
                    soul.name
                ),
                None,
                None,
            );
        }
    }

    /// Get the current mood for a character.
    pub fn mood(&self, client_id: ClientId) -> Option<MoodState> {
        self.souls.get(&client_id).map(|s| s.mood)
    }

    /// Get the social graph (for external queries/display).
    pub fn social_graph(&self) -> &SocialGraph {
        &self.social
    }

    /// Get the memory store (for external queries).
    pub fn memory_store(&self) -> &MemoryStore {
        &self.memory
    }

    // ── Alert API ────────────────────────────────────────────────────────────

    /// Override the default alert configuration.
    pub fn set_alert_config(&mut self, config: AlertConfig) {
        self.alert_config = config;
    }

    /// Return a reference to the current alert configuration.
    pub fn alert_config(&self) -> &AlertConfig {
        &self.alert_config
    }

    /// Drain all pending alerts (moves them out of the coordinator).
    /// Call this each UI/dashboard frame to collect newly generated alerts.
    pub fn drain_alerts(&mut self) -> Vec<Alert> {
        std::mem::take(&mut self.pending_alerts)
    }

    /// Peek at pending alerts without draining them.
    pub fn pending_alerts(&self) -> &[Alert] {
        &self.pending_alerts
    }

    /// Acknowledge (dismiss) a pending alert by index.
    /// Returns `true` if the index was valid.
    pub fn acknowledge_alert(&mut self, index: usize) -> bool {
        if let Some(alert) = self.pending_alerts.get_mut(index) {
            alert.acknowledged = true;
            true
        } else {
            false
        }
    }

    /// Mark a pending alert as a false alarm by index.
    /// Returns `true` if the index was valid.
    pub fn mark_false_alarm(&mut self, index: usize) -> bool {
        if let Some(alert) = self.pending_alerts.get_mut(index) {
            alert.false_alarm = true;
            alert.acknowledged = true;
            true
        } else {
            false
        }
    }

    // ── Internal alert detection ─────────────────────────────────────────────

    /// Run all alert-detection checks for a single character.
    /// This is called once per coordinator tick per registered character.
    fn check_alerts_for(&mut self, client_id: ClientId) {
        let Some(soul) = self.souls.get_mut(&client_id) else {
            return;
        };

        let now = Instant::now();
        let dedup = Duration::from_secs(self.alert_config.dedup_secs);

        // Helper: true if we should suppress this alert type due to deduplication.
        let should_suppress = |alert_state: &AlertState, alert_type: &AlertType| -> bool {
            alert_state
                .last_fired
                .get(alert_type)
                .is_some_and(|t| now.duration_since(*t) < dedup)
        };

        // --- MoodStuck: mood unchanged for > mood_stuck_hours ---
        {
            if soul.mood != soul.alert_state.last_mood {
                // Mood changed — reset the timer.
                soul.alert_state.last_mood = soul.mood;
                soul.alert_state.mood_since = now;
            } else {
                let stuck_threshold =
                    Duration::from_secs(self.alert_config.mood_stuck_hours * 3600);
                if now.duration_since(soul.alert_state.mood_since) > stuck_threshold
                    && !should_suppress(&soul.alert_state, &AlertType::MoodStuck)
                {
                    soul.alert_state
                        .last_fired
                        .insert(AlertType::MoodStuck, now);
                    let name = soul.name.clone();
                    let mood = soul.mood;
                    self.pending_alerts.push(Alert::new(
                        client_id,
                        AlertType::MoodStuck,
                        AlertSeverity::Warning,
                        format!(
                            "{name}: mood has been {mood:?} for >{} hours",
                            self.alert_config.mood_stuck_hours
                        ),
                    ));
                }
            }
        }

        // --- ChatSpam: >chat_spam_threshold messages in the last 60 seconds ---
        {
            // Evict timestamps older than 60 seconds.
            soul.alert_state
                .recent_chat_times
                .retain(|&t| now.duration_since(t) < Duration::from_secs(60));

            let count = soul.alert_state.recent_chat_times.len() as u32;
            if count > self.alert_config.chat_spam_threshold
                && !should_suppress(&soul.alert_state, &AlertType::ChatSpam)
            {
                soul.alert_state.last_fired.insert(AlertType::ChatSpam, now);
                let name = soul.name.clone();
                let threshold = self.alert_config.chat_spam_threshold;
                self.pending_alerts.push(Alert::new(
                    client_id,
                    AlertType::ChatSpam,
                    AlertSeverity::Warning,
                    format!(
                        "{name}: {count} messages in the last 60 seconds (threshold: {threshold})"
                    ),
                ));
            }
        }
    }

    /// Record that a character sent a chat message (used for spam detection).
    /// Call this whenever the coordinator produces a `Command::Say` for a character.
    fn record_chat_sent(&mut self, client_id: ClientId) {
        if let Some(soul) = self.souls.get_mut(&client_id) {
            soul.alert_state.recent_chat_times.push(Instant::now());
        }
    }

    /// Fire a `ProviderError` alert if the LLM provider has been unavailable
    /// for longer than the configured threshold.
    ///
    /// Callers (e.g., the LLM integration layer) should invoke this when they
    /// detect that the provider is down, passing the time the outage began.
    pub fn report_provider_error(&mut self, outage_started: Instant) {
        let threshold = Duration::from_secs(self.alert_config.provider_timeout_minutes * 60);
        let now = Instant::now();
        if now.duration_since(outage_started) < threshold {
            return;
        }

        // Coordinator-wide alert (character_id = 0).
        let dedup = Duration::from_secs(self.alert_config.dedup_secs);
        let already_fired = self.pending_alerts.iter().any(|a| {
            a.alert_type == AlertType::ProviderError && now.duration_since(a.timestamp) < dedup
        });

        if !already_fired {
            let minutes = self.alert_config.provider_timeout_minutes;
            self.pending_alerts.push(Alert::new(
                0,
                AlertType::ProviderError,
                AlertSeverity::Error,
                format!("LLM provider has been unavailable for >{minutes} minutes"),
            ));
        }
    }

    /// Fire an `UnexpectedBehavior` alert for a character.
    ///
    /// Call this from higher-level orchestration code when a character's
    /// actions deviate from its configured personality traits.
    pub fn report_unexpected_behavior(&mut self, client_id: ClientId, description: &str) {
        let now = Instant::now();
        let dedup = Duration::from_secs(self.alert_config.dedup_secs);

        // Deduplication: check existing pending alerts.
        let already_fired = self.pending_alerts.iter().any(|a| {
            a.character_id == client_id
                && a.alert_type == AlertType::UnexpectedBehavior
                && now.duration_since(a.timestamp) < dedup
        });

        if !already_fired {
            let name = self
                .souls
                .get(&client_id)
                .map_or_else(|| client_id.to_string(), |s| s.name.clone());
            self.pending_alerts.push(Alert::new(
                client_id,
                AlertType::UnexpectedBehavior,
                AlertSeverity::Warning,
                format!("{name}: {description}"),
            ));
        }
    }

    /// Fire a `MemoryFull` alert if a character's memory row count exceeds the
    /// configured percentage of `max_rows`.
    ///
    /// `current_rows` / `max_rows` must be in the same unit (e.g., both row
    /// counts from the SQLite memories table).
    pub fn check_memory_full(&mut self, client_id: ClientId, current_rows: usize, max_rows: usize) {
        if max_rows == 0 {
            return;
        }
        let pct = (current_rows * 100) / max_rows;
        if pct < self.alert_config.memory_full_percent as usize {
            return;
        }

        let now = Instant::now();
        let dedup = Duration::from_secs(self.alert_config.dedup_secs);
        let already_fired = self.pending_alerts.iter().any(|a| {
            a.character_id == client_id
                && a.alert_type == AlertType::MemoryFull
                && now.duration_since(a.timestamp) < dedup
        });

        if !already_fired {
            let name = self
                .souls
                .get(&client_id)
                .map_or_else(|| client_id.to_string(), |s| s.name.clone());
            let threshold = self.alert_config.memory_full_percent;
            self.pending_alerts.push(Alert::new(
                client_id,
                AlertType::MemoryFull,
                AlertSeverity::Warning,
                format!("{name}: memory table is {pct}% full (threshold: {threshold}%)"),
            ));
        }
    }

    /// Escalate: if `count` or more unacknowledged alerts exist, emit a
    /// synthetic Critical alert.  This implements the "chain multiple alerts →
    /// Critical" escalation path described in the spec.
    pub fn escalate_if_needed(&mut self, escalation_threshold: usize) {
        let unacked = self
            .pending_alerts
            .iter()
            .filter(|a| !a.acknowledged && !a.false_alarm)
            .count();

        if unacked >= escalation_threshold {
            let now = Instant::now();
            let already_critical = self.pending_alerts.iter().any(|a| {
                a.severity == AlertSeverity::Critical
                    && now.duration_since(a.timestamp) < Duration::from_secs(300)
            });

            if !already_critical {
                self.pending_alerts.push(Alert::new(
                    0,
                    AlertType::UnexpectedBehavior,
                    AlertSeverity::Critical,
                    format!(
                        "Escalation: {unacked} unacknowledged alerts ({escalation_threshold}+ threshold)"
                    ),
                ));
            }
        }
    }
}

fn truncate_utf8(input: &str, max_bytes: usize) -> &str {
    if input.len() <= max_bytes {
        return input;
    }

    let mut end = max_bytes;
    while !input.is_char_boundary(end) {
        end -= 1;
    }
    &input[..end]
}

/// Check if a client is currently in combat based on game state.
fn is_in_combat(state: &GameState) -> bool {
    !matches!(
        state.combat_status,
        textquest_common::combat::CombatStatus::Idle
    )
}

/// Extract zone name from game state (placeholder until zone tracking is added).
fn zone_from_state(_state: &GameState) -> &'static str {
    "unknown"
}

#[cfg(test)]
mod tests {
    use super::*;
    use textquest_common::combat::CombatStatus;
    use textquest_common::nav::NavStatus;
    use textquest_common::soul::{PersonalityTraits, SpeechStyle};
    use textquest_common::types::SpawnData;

    fn make_game_state(client_id: ClientId) -> GameState {
        GameState {
            client_id,
            local_player: Some(SpawnData {
                displayed_name: "TestChar".to_string(),
                name: "TestChar".to_string(),
                level: 60,
                ..SpawnData::default()
            }),
            target: None,
            nearby_spawns: vec![],
            timestamp_ms: 0,
            nav_status: NavStatus::Idle,
            combat_status: CombatStatus::Idle,
            zone_short_name: "test".into(),
            zone_long_name: "Test Zone".into(),
        }
    }

    fn make_soul_config(enabled: bool) -> SoulConfig {
        SoulConfig {
            enabled,
            ..SoulConfig::default()
        }
    }

    fn make_char_config(name: &str) -> CharacterSoulConfig {
        CharacterSoulConfig {
            name: name.to_string(),
            traits: PersonalityTraits::default(),
            speech: SpeechStyle::default(),
            edginess: None,
            backstory: String::new(),
            quirks: Vec::new(),
        }
    }

    fn make_coordinator(enabled: bool) -> SoulCoordinator {
        let dir = tempfile::tempdir().unwrap();
        let db_path = dir.path().join("test_memory.db");
        let config = make_soul_config(enabled);
        // Leak the tempdir so it doesn't get deleted while coordinator lives
        let dir = Box::leak(Box::new(dir));
        let _ = dir; // suppress warning
        SoulCoordinator::new(config, &db_path).unwrap()
    }

    #[test]
    fn new_coordinator_creates_successfully() {
        let dir = tempfile::tempdir().unwrap();
        let db_path = dir.path().join("test.db");
        let config = make_soul_config(false);
        let coord = SoulCoordinator::new(config, &db_path);
        assert!(coord.is_ok());
    }

    #[test]
    fn register_character_stores_soul() {
        let mut coord = make_coordinator(true);
        let char_config = make_char_config("Warrior01");
        coord.register_character(1, &char_config);
        assert!(coord.mood(1).is_some());
        assert_eq!(coord.mood(1).unwrap(), MoodState::Neutral);
    }

    #[test]
    fn mood_returns_none_for_unregistered() {
        let coord = make_coordinator(true);
        assert!(coord.mood(99).is_none());
    }

    #[test]
    fn tick_returns_empty_when_disabled() {
        let mut coord = make_coordinator(false);
        coord.register_character(1, &make_char_config("Test"));
        let mut states = HashMap::new();
        states.insert(1, make_game_state(1));
        let (cmds, _alerts) = coord.tick(&states);
        assert!(cmds.is_empty());
    }

    #[test]
    fn tick_increments_tick_count() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("Test"));
        let mut states = HashMap::new();
        states.insert(1, make_game_state(1));
        coord.tick(&states);
        assert_eq!(coord.tick_count, 1);
        coord.tick(&states);
        assert_eq!(coord.tick_count, 2);
    }

    #[test]
    fn on_game_event_updates_mood() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("Test"));

        let initial_mood = coord.mood(1).unwrap();
        // Death events should significantly affect mood
        coord.on_game_event(
            1,
            SoulEvent::Death {
                killer: Some("a dragon".into()),
                zone: "permafrost".into(),
            },
        );
        // Mood may or may not change depending on personality engine,
        // but the function should not panic
        let _ = coord.mood(1).unwrap();
        let _ = initial_mood; // suppress unused
    }

    #[test]
    fn on_game_event_ignores_unknown_client() {
        let mut coord = make_coordinator(true);
        // Should not panic for unregistered client
        coord.on_game_event(
            99,
            SoulEvent::Kill {
                target: "orc".into(),
                zone: "test".into(),
            },
        );
    }

    #[test]
    fn on_player_message_ignores_when_disabled() {
        let mut coord = make_coordinator(true);
        coord.config.player_chat_enabled = false;
        coord.register_character(1, &make_char_config("Test"));
        // Should not enqueue anything
        coord.on_player_message(1, "Dave", "Hello!", "say");
        assert_eq!(coord.llm_queue.pending_count(), 0);
    }

    #[test]
    fn on_player_message_enqueues_response() {
        let mut coord = make_coordinator(true);
        coord.config.player_chat_enabled = true;
        coord.register_character(1, &make_char_config("Test"));
        coord.on_player_message(1, "Dave", "Hey there!", "say");
        assert_eq!(coord.llm_queue.pending_count(), 1);
    }

    #[test]
    fn on_player_message_ignores_unknown_client() {
        let mut coord = make_coordinator(true);
        coord.config.player_chat_enabled = true;
        // Should not panic for unregistered client
        coord.on_player_message(99, "Dave", "Hello!", "say");
        assert_eq!(coord.llm_queue.pending_count(), 0);
    }

    #[test]
    fn on_player_message_ignores_empty_message() {
        let mut coord = make_coordinator(true);
        coord.config.player_chat_enabled = true;
        coord.register_character(1, &make_char_config("Test"));
        coord.on_player_message(1, "Dave", "   ", "say");
        assert_eq!(coord.llm_queue.pending_count(), 0);
    }

    #[test]
    fn truncate_utf8_does_not_split_multibyte_codepoint() {
        let input = "hello🙂";
        let truncated = truncate_utf8(input, 6);
        assert_eq!(truncated, "hello");
    }

    #[test]
    fn social_graph_accessible() {
        let coord = make_coordinator(true);
        let graph = coord.social_graph();
        // Fresh coordinator has no relationships
        assert!(graph.relationships_for("Nobody").is_empty());
    }

    #[test]
    fn memory_store_accessible() {
        let coord = make_coordinator(true);
        let _store = coord.memory_store();
        // Should not panic
    }

    #[test]
    fn is_in_combat_helper() {
        let mut state = make_game_state(1);
        state.combat_status = CombatStatus::Idle;
        assert!(!is_in_combat(&state));

        state.combat_status = CombatStatus::Engaging { target_id: 1 };
        assert!(is_in_combat(&state));
    }

    #[test]
    fn zone_from_state_returns_unknown() {
        let state = make_game_state(1);
        assert_eq!(zone_from_state(&state), "unknown");
    }

    #[test]
    fn register_multiple_characters() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("Alpha"));
        coord.register_character(2, &make_char_config("Beta"));
        coord.register_character(3, &make_char_config("Gamma"));

        assert!(coord.mood(1).is_some());
        assert!(coord.mood(2).is_some());
        assert!(coord.mood(3).is_some());
    }

    #[test]
    fn tick_skips_clients_without_game_state() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("Test"));
        // Empty states map — no game state for client 1
        let states = HashMap::new();
        let (cmds, _alerts) = coord.tick(&states);
        // Should not panic, just skip
        assert!(cmds.is_empty());
    }

    // ── Alert system tests ────────────────────────────────────────────────────

    #[test]
    fn alert_config_defaults_are_sane() {
        let cfg = AlertConfig::default();
        assert_eq!(cfg.mood_stuck_hours, 2);
        assert_eq!(cfg.chat_spam_threshold, 5);
        assert_eq!(cfg.memory_full_percent, 90);
        assert_eq!(cfg.provider_timeout_minutes, 30);
        assert_eq!(cfg.dedup_secs, 300);
    }

    #[test]
    fn new_coordinator_starts_with_no_alerts() {
        let coord = make_coordinator(true);
        assert!(coord.pending_alerts().is_empty());
    }

    #[test]
    fn drain_alerts_empties_queue() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("Test"));

        // Manually inject an alert.
        coord.pending_alerts.push(Alert::new(
            1,
            AlertType::MoodStuck,
            AlertSeverity::Warning,
            "test alert",
        ));

        let drained = coord.drain_alerts();
        assert_eq!(drained.len(), 1);
        assert!(coord.pending_alerts().is_empty());
    }

    #[test]
    fn acknowledge_alert_sets_flag() {
        let mut coord = make_coordinator(true);
        coord.pending_alerts.push(Alert::new(
            1,
            AlertType::MoodStuck,
            AlertSeverity::Warning,
            "test",
        ));

        assert!(coord.acknowledge_alert(0));
        assert!(coord.pending_alerts()[0].acknowledged);
    }

    #[test]
    fn acknowledge_out_of_range_returns_false() {
        let mut coord = make_coordinator(true);
        assert!(!coord.acknowledge_alert(99));
    }

    #[test]
    fn mark_false_alarm_sets_both_flags() {
        let mut coord = make_coordinator(true);
        coord.pending_alerts.push(Alert::new(
            1,
            AlertType::ChatSpam,
            AlertSeverity::Warning,
            "spam",
        ));

        assert!(coord.mark_false_alarm(0));
        let alert = &coord.pending_alerts()[0];
        assert!(alert.false_alarm);
        assert!(alert.acknowledged);
    }

    #[test]
    fn mood_stuck_alert_fires_after_threshold() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("StuckChar"));

        // Set alert config to 0 hours so it fires immediately on first check.
        coord.set_alert_config(AlertConfig {
            mood_stuck_hours: 0,
            dedup_secs: 0,
            ..AlertConfig::default()
        });

        // Manually set the mood_since to far in the past.
        if let Some(soul) = coord.souls.get_mut(&1) {
            soul.alert_state.mood_since = Instant::now() - Duration::from_secs(10);
        }

        coord.check_alerts_for(1);

        let alerts = coord.pending_alerts();
        assert!(
            alerts.iter().any(|a| a.alert_type == AlertType::MoodStuck),
            "expected MoodStuck alert"
        );
    }

    #[test]
    fn mood_stuck_alert_does_not_fire_when_mood_changes() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("ChangeChar"));

        coord.set_alert_config(AlertConfig {
            mood_stuck_hours: 0,
            dedup_secs: 0,
            ..AlertConfig::default()
        });

        // Change the mood so last_mood != current mood; check_alerts resets timer.
        if let Some(soul) = coord.souls.get_mut(&1) {
            soul.mood = MoodState::Happy;
            soul.alert_state.last_mood = MoodState::Angry; // different
            soul.alert_state.mood_since = Instant::now() - Duration::from_secs(10);
        }

        coord.check_alerts_for(1);

        // After the first call mood and last_mood are both Happy — timer reset.
        // A second check immediately after should NOT fire (0-second threshold
        // could still fire, but timer was just reset so duration_since ≈ 0).
        assert!(
            !coord
                .pending_alerts()
                .iter()
                .any(|a| a.alert_type == AlertType::MoodStuck),
            "MoodStuck should not fire when mood just changed"
        );
    }

    #[test]
    fn chat_spam_alert_fires_over_threshold() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("SpamChar"));

        coord.set_alert_config(AlertConfig {
            chat_spam_threshold: 3,
            dedup_secs: 0,
            ..AlertConfig::default()
        });

        // Inject 4 recent chat times (> threshold of 3).
        if let Some(soul) = coord.souls.get_mut(&1) {
            let now = Instant::now();
            soul.alert_state.recent_chat_times = vec![now, now, now, now];
        }

        coord.check_alerts_for(1);

        assert!(
            coord
                .pending_alerts()
                .iter()
                .any(|a| a.alert_type == AlertType::ChatSpam),
            "expected ChatSpam alert"
        );
    }

    #[test]
    fn chat_spam_alert_does_not_fire_at_threshold() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("OkChar"));

        coord.set_alert_config(AlertConfig {
            chat_spam_threshold: 5,
            dedup_secs: 0,
            ..AlertConfig::default()
        });

        // Exactly 5 messages — not over the threshold.
        if let Some(soul) = coord.souls.get_mut(&1) {
            let now = Instant::now();
            soul.alert_state.recent_chat_times = vec![now; 5];
        }

        coord.check_alerts_for(1);

        assert!(
            !coord
                .pending_alerts()
                .iter()
                .any(|a| a.alert_type == AlertType::ChatSpam),
            "ChatSpam should not fire at exactly threshold"
        );
    }

    #[test]
    fn chat_spam_evicts_old_timestamps() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("OldSpam"));

        coord.set_alert_config(AlertConfig {
            chat_spam_threshold: 3,
            dedup_secs: 0,
            ..AlertConfig::default()
        });

        // Inject 4 timestamps that are 2 minutes old — should be evicted.
        if let Some(soul) = coord.souls.get_mut(&1) {
            let old = Instant::now() - Duration::from_secs(120);
            soul.alert_state.recent_chat_times = vec![old, old, old, old];
        }

        coord.check_alerts_for(1);

        assert!(
            !coord
                .pending_alerts()
                .iter()
                .any(|a| a.alert_type == AlertType::ChatSpam),
            "old timestamps should be evicted, no ChatSpam"
        );
    }

    #[test]
    fn alert_deduplication_suppresses_repeat() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("DedupChar"));

        // 5-minute dedup window.
        coord.set_alert_config(AlertConfig {
            mood_stuck_hours: 0,
            dedup_secs: 300,
            ..AlertConfig::default()
        });

        if let Some(soul) = coord.souls.get_mut(&1) {
            soul.alert_state.mood_since = Instant::now() - Duration::from_secs(10);
        }

        coord.check_alerts_for(1);
        let count_after_first = coord
            .pending_alerts()
            .iter()
            .filter(|a| a.alert_type == AlertType::MoodStuck)
            .count();

        // Second immediate check — dedup should suppress.
        coord.check_alerts_for(1);
        let count_after_second = coord
            .pending_alerts()
            .iter()
            .filter(|a| a.alert_type == AlertType::MoodStuck)
            .count();

        assert_eq!(count_after_first, 1, "first check should fire once");
        assert_eq!(count_after_second, 1, "second check should be deduplicated");
    }

    #[test]
    fn provider_error_alert_fires_when_outage_exceeds_threshold() {
        let mut coord = make_coordinator(true);

        coord.set_alert_config(AlertConfig {
            provider_timeout_minutes: 0,
            dedup_secs: 0,
            ..AlertConfig::default()
        });

        // Outage started 5 seconds ago — exceeds 0-minute threshold.
        let outage_start = Instant::now() - Duration::from_secs(5);
        coord.report_provider_error(outage_start);

        assert!(
            coord
                .pending_alerts()
                .iter()
                .any(|a| a.alert_type == AlertType::ProviderError),
            "expected ProviderError alert"
        );
    }

    #[test]
    fn provider_error_alert_does_not_fire_before_threshold() {
        let mut coord = make_coordinator(true);

        // 30-minute threshold, outage only 1 second old.
        coord.set_alert_config(AlertConfig::default());
        let outage_start = Instant::now() - Duration::from_secs(1);
        coord.report_provider_error(outage_start);

        assert!(
            !coord
                .pending_alerts()
                .iter()
                .any(|a| a.alert_type == AlertType::ProviderError),
            "ProviderError should not fire before threshold"
        );
    }

    #[test]
    fn unexpected_behavior_alert_fires() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("Weirdo"));

        coord.report_unexpected_behavior(1, "jumped off a cliff unprovoked");

        let alerts = coord.pending_alerts();
        assert!(
            alerts
                .iter()
                .any(|a| a.alert_type == AlertType::UnexpectedBehavior && a.character_id == 1),
            "expected UnexpectedBehavior alert"
        );
    }

    #[test]
    fn unexpected_behavior_deduplicates() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("Weirdo"));

        coord.set_alert_config(AlertConfig {
            dedup_secs: 300,
            ..AlertConfig::default()
        });

        coord.report_unexpected_behavior(1, "first oddity");
        coord.report_unexpected_behavior(1, "second oddity");

        let count = coord
            .pending_alerts()
            .iter()
            .filter(|a| a.alert_type == AlertType::UnexpectedBehavior && a.character_id == 1)
            .count();

        assert_eq!(count, 1, "unexpected behavior should be deduplicated");
    }

    #[test]
    fn memory_full_alert_fires_at_threshold() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("MemChar"));

        coord.set_alert_config(AlertConfig {
            memory_full_percent: 90,
            dedup_secs: 0,
            ..AlertConfig::default()
        });

        // 95 out of 100 = 95% full — exceeds 90%.
        coord.check_memory_full(1, 95, 100);

        assert!(
            coord
                .pending_alerts()
                .iter()
                .any(|a| a.alert_type == AlertType::MemoryFull),
            "expected MemoryFull alert"
        );
    }

    #[test]
    fn memory_full_alert_does_not_fire_below_threshold() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("MemChar"));

        coord.set_alert_config(AlertConfig {
            memory_full_percent: 90,
            dedup_secs: 0,
            ..AlertConfig::default()
        });

        // 85% — below threshold.
        coord.check_memory_full(1, 85, 100);

        assert!(
            !coord
                .pending_alerts()
                .iter()
                .any(|a| a.alert_type == AlertType::MemoryFull),
            "MemoryFull should not fire below threshold"
        );
    }

    #[test]
    fn memory_full_handles_zero_max() {
        let mut coord = make_coordinator(true);
        // max_rows = 0 should not panic or fire.
        coord.check_memory_full(1, 0, 0);
        assert!(coord.pending_alerts().is_empty());
    }

    #[test]
    fn escalation_fires_critical_alert() {
        let mut coord = make_coordinator(true);

        // Add 3 unacknowledged alerts.
        for i in 0..3u32 {
            coord.pending_alerts.push(Alert::new(
                i as ClientId,
                AlertType::MoodStuck,
                AlertSeverity::Warning,
                format!("alert {i}"),
            ));
        }

        coord.escalate_if_needed(3);

        assert!(
            coord
                .pending_alerts()
                .iter()
                .any(|a| a.severity == AlertSeverity::Critical),
            "escalation should produce a Critical alert"
        );
    }

    #[test]
    fn escalation_does_not_fire_below_threshold() {
        let mut coord = make_coordinator(true);

        // Add 2 alerts, threshold is 3.
        for i in 0..2u32 {
            coord.pending_alerts.push(Alert::new(
                i as ClientId,
                AlertType::MoodStuck,
                AlertSeverity::Warning,
                format!("alert {i}"),
            ));
        }

        coord.escalate_if_needed(3);

        assert!(
            !coord
                .pending_alerts()
                .iter()
                .any(|a| a.severity == AlertSeverity::Critical),
            "escalation should not fire below threshold"
        );
    }

    #[test]
    fn escalation_skips_acknowledged_alerts() {
        let mut coord = make_coordinator(true);

        // Add 3 alerts but acknowledge all of them.
        for i in 0..3u32 {
            let mut alert = Alert::new(
                i as ClientId,
                AlertType::MoodStuck,
                AlertSeverity::Warning,
                format!("alert {i}"),
            );
            alert.acknowledged = true;
            coord.pending_alerts.push(alert);
        }

        coord.escalate_if_needed(3);

        assert!(
            !coord
                .pending_alerts()
                .iter()
                .any(|a| a.severity == AlertSeverity::Critical),
            "acknowledged alerts should not count toward escalation"
        );
    }

    #[test]
    fn set_alert_config_replaces_config() {
        let mut coord = make_coordinator(true);
        let custom = AlertConfig {
            mood_stuck_hours: 5,
            chat_spam_threshold: 10,
            memory_full_percent: 80,
            provider_timeout_minutes: 60,
            dedup_secs: 120,
        };
        coord.set_alert_config(custom);
        assert_eq!(coord.alert_config().mood_stuck_hours, 5);
        assert_eq!(coord.alert_config().chat_spam_threshold, 10);
        assert_eq!(coord.alert_config().memory_full_percent, 80);
    }

    #[test]
    fn alert_severity_ordering() {
        assert!(AlertSeverity::Info < AlertSeverity::Warning);
        assert!(AlertSeverity::Warning < AlertSeverity::Error);
        assert!(AlertSeverity::Error < AlertSeverity::Critical);
    }

    #[test]
    fn record_chat_sent_populates_alert_state() {
        let mut coord = make_coordinator(true);
        coord.register_character(1, &make_char_config("ChatChar"));

        coord.record_chat_sent(1);
        coord.record_chat_sent(1);

        let soul = coord.souls.get(&1).unwrap();
        assert_eq!(soul.alert_state.recent_chat_times.len(), 2);
    }
}
