#!/usr/bin/env bash
# Verify completed AutoShip workers + open PRs.
# Safe defaults: skip if diff empty, skip if no commits, skip if PR exists.
set -uo pipefail

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"

processed=0
prs=0
skipped=0
blocked=0

for WS in .autoship/workspaces/issue-*; do
  [[ -d "$WS" ]] || continue
  KEY=$(basename "$WS")
  N="${KEY#issue-}"
  RESULT="$WS/AUTOSHIP_RESULT.md"
  PANE="$WS/pane.log"

  # Must have result file AND COMPLETE marker in pane.log
  [[ -f "$RESULT" ]] || continue
  grep -q "^COMPLETE$" "$PANE" 2>/dev/null || continue

  ((processed++))

  # Skip if PR already exists for this branch
  if gh pr list --head "autoship/$KEY" --state all --json number -q '.[0].number' 2>/dev/null | grep -q .; then
    echo "SKIP $N: PR exists"
    ((skipped++))
    continue
  fi

  cd "$WS"

  # Must have at least one commit beyond origin/master
  COMMITS=$(git rev-list --count HEAD ^origin/master 2>/dev/null || echo 0)
  if [[ "$COMMITS" -eq 0 ]]; then
    echo "SKIP $N: no commits"
    ((skipped++))
    cd "$ROOT"; continue
  fi

  # Diff non-empty?
  if [[ -z "$(git diff --stat origin/master 2>/dev/null)" ]]; then
    echo "SKIP $N: empty diff"
    ((skipped++))
    cd "$ROOT"; continue
  fi

  # Push branch
  if ! git push -u origin "autoship/$KEY" 2>&1 | tail -3; then
    echo "BLOCK $N: push failed"
    ((blocked++))
    cd "$ROOT"; continue
  fi

  # Get issue title for PR
  TITLE=$(gh issue view "$N" --json title -q .title 2>/dev/null)
  [[ -z "$TITLE" ]] && TITLE="autoship work for #$N"

  # Build PR body
  BODY_FILE=$(mktemp)
  {
    echo "Closes #$N"
    echo
    echo "## AutoShip Result"
    echo
    cat AUTOSHIP_RESULT.md
    echo
    echo "## Diff Summary"
    echo '```'
    git diff --stat origin/master | tail -20
    echo '```'
    echo
    echo "_Auto-generated by AutoShip (codex-gpt-5.4-mini)._"
  } > "$BODY_FILE"

  if PR_URL=$(gh pr create \
       --title "autoship #$N: ${TITLE:0:80}" \
       --body-file "$BODY_FILE" \
       --label autoship \
       --head "autoship/$KEY" \
       --base master 2>&1); then
    echo "PR $N: $PR_URL"
    ((prs++))
  else
    echo "BLOCK $N: PR create failed: $PR_URL"
    ((blocked++))
  fi

  rm -f "$BODY_FILE"
  cd "$ROOT"
done

echo "---"
echo "Processed: $processed | PRs: $prs | Skipped: $skipped | Blocked: $blocked"
