/// HTTP-based LLM provider — local ollama-compatible API clients.
pub mod api_client;
/// Trait-based fallback responder — generates text without an LLM API.
pub mod fallback;
/// Priority queue for LLM requests — ensures high-priority requests are
/// processed first.
pub mod priority_queue;
/// Gemma/local-LLM response validation before operator display.
pub mod validator;

use anyhow::Result;
use textquest_common::soul::{MoodState, PersonalityTraits, SpeechStyle};

pub use validator::{ValidationError, validate_observation};

/// Priority level for LLM requests. Higher priority = processed first.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum LlmPriority {
    /// Idle chatter, ambient flavor text
    Low = 0,
    /// Game events, combat reactions
    Medium = 1,
    /// Real player interaction — always highest priority
    High = 2,
}

/// Situation context for the LLM to generate an appropriate response.
#[derive(Debug, Clone)]
pub enum Situation {
    /// Responding to a real player's tell/say
    PlayerChat {
        /// Name of the player who sent the message.
        player_name: String,
        /// The message text.
        message: String,
        /// Chat channel (say, tell, group, etc.).
        channel: String,
    },
    /// Reacting to a game event
    GameEvent {
        /// Human-readable description of the game event.
        description: String,
    },
    /// Idle chatter / flavor text
    IdleChatter,
    /// Reacting to another bot character
    BotChat {
        /// Name of the bot character who sent the message.
        character_name: String,
        /// The message text.
        message: String,
    },
    /// Combat reaction (kill, death, loot)
    CombatReaction {
        /// Description of the combat event (kill, death, loot).
        description: String,
    },
    /// Fleet-wide event commentary for Discord (kills, wipes, milestones)
    FleetCommentary {
        /// Summary of the fleet event.
        event_summary: String,
    },
}

/// Request to generate text via LLM or fallback.
#[derive(Debug, Clone)]
pub struct LlmRequest {
    /// Character name for prompt context.
    pub character_name: String,
    /// Personality trait vector (openness, conscientiousness, etc.).
    pub traits: PersonalityTraits,
    /// Current emotional state.
    pub mood: MoodState,
    /// How this character speaks (formal, casual, etc.).
    pub speech_style: SpeechStyle,
    /// What triggered this request.
    pub situation: Situation,
    /// Processing priority.
    pub priority: LlmPriority,
    /// Recent memory context (serialized snippets for LLM prompt building)
    pub memory_context: Vec<String>,
    /// Backstory snippet for this character
    pub backstory: String,
}

/// Response from an LLM provider (or fallback).
#[derive(Debug, Clone)]
pub struct LlmResponse {
    /// Generated text to speak or emote.
    pub text: String,
    /// Whether this was generated by a real LLM or the trait-based fallback
    pub from_llm: bool,
    /// Tokens used (0 for fallback)
    pub tokens_used: u32,
}

/// Trait for LLM providers. Sync in Phase 1 (no async runtime).
/// Implementations: `TraitDrivenResponder` (fallback), future local model
/// clients.
pub trait LlmProvider {
    /// Generate a response for the given request.
    /// Returns Ok(response) or Err if generation fails entirely.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    fn generate(&mut self, request: &LlmRequest) -> Result<LlmResponse>;

    /// Provider name for logging/diagnostics.
    fn name(&self) -> &str;

    /// Whether this provider is currently available (API key set, quota
    /// remaining, etc.)
    fn is_available(&self) -> bool;
}

#[cfg(test)]
mod tests {
    use super::*;
    use textquest_common::soul::{MoodState, PersonalityTraits, SpeechStyle};

    #[test]
    fn llm_priority_ordering() {
        assert!(LlmPriority::Low < LlmPriority::Medium);
        assert!(LlmPriority::Medium < LlmPriority::High);
        assert!(LlmPriority::Low < LlmPriority::High);
    }

    #[test]
    fn llm_priority_equality() {
        assert_eq!(LlmPriority::Low, LlmPriority::Low);
        assert_ne!(LlmPriority::Low, LlmPriority::High);
    }

    #[test]
    fn llm_priority_copy_clone() {
        let p = LlmPriority::Medium;
        let c = p; // Copy
        assert_eq!(p, c);
        let copy = p;
        assert_eq!(p, copy);
    }

    #[test]
    fn llm_priority_debug() {
        assert_eq!(format!("{:?}", LlmPriority::Low), "Low");
        assert_eq!(format!("{:?}", LlmPriority::Medium), "Medium");
        assert_eq!(format!("{:?}", LlmPriority::High), "High");
    }

    #[test]
    fn situation_variants_debug_and_clone() {
        let situations = [
            Situation::PlayerChat {
                player_name: "Dave".into(),
                message: "Hello".into(),
                channel: "say".into(),
            },
            Situation::GameEvent {
                description: "ding".into(),
            },
            Situation::IdleChatter,
            Situation::BotChat {
                character_name: "Grimjaw".into(),
                message: "Hey".into(),
            },
            Situation::CombatReaction {
                description: "killed orc".into(),
            },
        ];
        for s in &situations {
            let _ = format!("{:?}", s);
        }
    }

    #[test]
    fn llm_request_construction() {
        let req = LlmRequest {
            character_name: "TestChar".into(),
            traits: PersonalityTraits::default(),
            mood: MoodState::Neutral,
            speech_style: SpeechStyle::default(),
            situation: Situation::IdleChatter,
            priority: LlmPriority::Low,
            memory_context: vec!["memory1".into()],
            backstory: "A brave warrior".into(),
        };
        assert_eq!(req.character_name, "TestChar");
        assert_eq!(req.priority, LlmPriority::Low);
        assert_eq!(req.memory_context.len(), 1);
        let _ = format!("{:?}", req);
    }

    #[test]
    fn llm_response_construction() {
        let resp = LlmResponse {
            text: "Hail, traveler!".into(),
            from_llm: false,
            tokens_used: 0,
        };
        assert!(!resp.from_llm);
        assert_eq!(resp.tokens_used, 0);
        assert_eq!(resp.text, "Hail, traveler!");
        let _ = format!("{:?}", resp);
    }

    #[test]
    fn llm_response_from_real_llm() {
        let resp = LlmResponse {
            text: "Generated text".into(),
            from_llm: true,
            tokens_used: 150,
        };
        assert!(resp.from_llm);
        assert_eq!(resp.tokens_used, 150);
    }

    #[test]
    fn llm_request_clone() {
        let req = LlmRequest {
            character_name: "Test".into(),
            traits: PersonalityTraits::default(),
            mood: MoodState::Happy,
            speech_style: SpeechStyle::default(),
            situation: Situation::IdleChatter,
            priority: LlmPriority::High,
            memory_context: vec![],
            backstory: String::new(),
        };
        assert_eq!(req.character_name, "Test");
        assert_eq!(req.priority, LlmPriority::High);
    }
}
