//! Named pipe CLIENT (orchestrator side).
//!
//! Connects to a named pipe created by the injected DLL and sends commands,
//! optionally waiting for a response. On non-Windows platforms this is a
//! compile-only stub.

use anyhow::Result;
#[cfg(test)]
use std::collections::{HashMap, VecDeque};
#[cfg(test)]
use std::sync::{Mutex, OnceLock};
#[cfg(windows)]
use textquest_common::ipc::IpcResponse;
#[cfg(windows)]
use textquest_common::protocol;
use textquest_common::{
    ipc::{Command, CorrelationIdGenerator, IpcCommand, Response},
    types::ClientId,
};

/// Sends commands to an injected DLL via named pipe.
pub struct CommandPipe {
    client_id: ClientId,
    correlation_ids: CorrelationIdGenerator,
    #[cfg(windows)]
    handle: windows::Win32::Foundation::HANDLE,
}

#[cfg(test)]
fn test_ipc_response_queues() -> &'static Mutex<HashMap<ClientId, HashMap<u64, VecDeque<Response>>>>
{
    static TEST_IPC_RESPONSES: OnceLock<
        Mutex<HashMap<ClientId, HashMap<u64, VecDeque<Response>>>>,
    > = OnceLock::new();
    TEST_IPC_RESPONSES.get_or_init(|| Mutex::new(HashMap::new()))
}

#[cfg(test)]
fn take_test_ipc_response(client_id: ClientId, correlation_id: u64) -> Option<Response> {
    let mut queues = test_ipc_response_queues().lock().ok()?;
    let per_client = queues.get_mut(&client_id)?;
    let queue = per_client.get_mut(&correlation_id)?;
    let response = queue.pop_front();
    if queue.is_empty() {
        per_client.remove(&correlation_id);
    }
    if per_client.is_empty() {
        queues.remove(&client_id);
    }
    response
}

#[cfg(all(not(windows), test))]
pub(crate) fn queue_test_ipc_response(
    client_id: ClientId,
    correlation_id: u64,
    response: Response,
) {
    let mut queues = test_ipc_response_queues()
        .lock()
        .expect("test IPC response queue mutex should be available");
    let per_client = queues.entry(client_id).or_default();
    per_client
        .entry(correlation_id)
        .or_default()
        .push_back(response);
}

#[cfg(all(not(windows), test))]
pub(crate) fn clear_test_ipc_responses() {
    let mut queues = test_ipc_response_queues()
        .lock()
        .expect("test IPC response queue mutex should be available");
    queues.clear();
}

impl CommandPipe {
    /// Connect to the named pipe for a specific client.
    ///
    /// Pipe name is generated by `textquest_common::ipc::pipe_name(session_id,
    /// client_id)` and includes both the session ID and the client ID for
    /// disambiguation.
    ///
    /// IMPORTANT: `client_id` must be the EQ process PID, not a sequential
    /// index. The injected DLL creates its pipe using `std::process::id()`
    /// (i.e., the PID) as the `client_id`. The orchestrator must match this
    /// by passing the PID discovered via `find_processes_by_name`.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    pub fn connect(client_id: ClientId, session_id: u64) -> Result<Self> {
        #[cfg(windows)]
        {
            use windows::{
                Win32::{
                    Foundation::GENERIC_READ,
                    Storage::FileSystem::{CreateFileA, FILE_ATTRIBUTE_NORMAL, OPEN_EXISTING},
                },
                core::PCSTR,
            };

            let pipe_name = format!(
                "{}\0",
                textquest_common::ipc::pipe_name(session_id, client_id)
            );

            let handle = unsafe {
                CreateFileA(
                    PCSTR(pipe_name.as_ptr()),
                    GENERIC_READ.0 | windows::Win32::Foundation::GENERIC_WRITE.0,
                    windows::Win32::Storage::FileSystem::FILE_SHARE_NONE,
                    None,
                    OPEN_EXISTING,
                    FILE_ATTRIBUTE_NORMAL,
                    None,
                )
            }?;

            Ok(Self {
                client_id,
                correlation_ids: CorrelationIdGenerator::new(),
                handle,
            })
        }

        #[cfg(not(windows))]
        {
            let _ = session_id;
            Ok(Self {
                client_id,
                correlation_ids: CorrelationIdGenerator::new(),
            })
        }
    }

    /// Send a command and wait for response.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    pub fn send(&self, cmd: &Command) -> Result<Response> {
        let correlation_id = self.correlation_ids.next_id();
        let (response, echoed_correlation_id) = self.send_correlated(cmd, correlation_id)?;
        if echoed_correlation_id != Some(correlation_id) {
            anyhow::bail!(
                "response correlation mismatch for client {}: sent {}, received {:?}",
                self.client_id,
                correlation_id,
                echoed_correlation_id
            );
        }
        Ok(response)
    }

    /// Send a command with a correlation ID and wait for a response.
    ///
    /// Returns the response payload and the echoed correlation ID (if any).
    ///
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    pub fn send_correlated(
        &self,
        cmd: &Command,
        correlation_id: u64,
    ) -> Result<(Response, Option<u64>)> {
        self.send_ipc(&IpcCommand::with_correlation(cmd.clone(), correlation_id))
    }

    /// Internal: encode an `IpcCommand`, write it to the pipe, read back an
    /// `IpcResponse`, and return `(response, correlation_id)`.
    fn send_ipc(&self, ipc_cmd: &IpcCommand) -> Result<(Response, Option<u64>)> {
        #[cfg(all(not(windows), test))]
        if let Some(correlation_id) = ipc_cmd.correlation_id {
            if let Some(response) = take_test_ipc_response(self.client_id, correlation_id) {
                return Ok((response, Some(correlation_id)));
            }
        }

        #[cfg(windows)]
        {
            use windows::Win32::Storage::FileSystem::{ReadFile, WriteFile};

            let data = protocol::encode(ipc_cmd)
                .map_err(|e| anyhow::anyhow!("failed to encode command: {e}"))?;

            // Pipe is in byte mode (PIPE_TYPE_BYTE), so partial writes are
            // possible. Loop until all bytes are written.
            let mut offset = 0usize;
            while offset < data.len() {
                let mut written: u32 = 0;
                unsafe {
                    WriteFile(self.handle, Some(&data[offset..]), Some(&mut written), None)?;
                }
                if written == 0 {
                    return Err(anyhow::anyhow!(
                        "WriteFile returned 0 bytes written for client {}",
                        self.client_id
                    ));
                }
                offset += written as usize;
            }

            // Read response (buffer sized to MAX_MESSAGE_SIZE + protocol header)
            let mut buf =
                vec![0u8; protocol::MAX_MESSAGE_SIZE as usize + protocol::FRAME_HEADER_SIZE];
            let mut bytes_read: u32 = 0;
            unsafe {
                ReadFile(self.handle, Some(&mut buf), Some(&mut bytes_read), None)?;
            }

            let (ipc_resp, _) = protocol::decode_frame::<IpcResponse>(&buf[..bytes_read as usize])
                .map_err(|error| {
                    anyhow::anyhow!(
                        "Protocol error decoding response from client {}: {error}",
                        self.client_id
                    )
                })?
                .ok_or_else(|| {
                    anyhow::anyhow!("Incomplete response frame from client {}", self.client_id)
                })?;

            Ok((ipc_resp.response, ipc_resp.correlation_id))
        }

        #[cfg(not(windows))]
        {
            let _ = (self.client_id, ipc_cmd);
            Ok((
                Response::Error {
                    message: "Not implemented (non-Windows stub)".into(),
                },
                None,
            ))
        }
    }

    /// Send the raw 32-byte session token for authentication handshake.
    /// Must be called once after connecting, before sending any commands.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    pub fn send_raw_token(&self, token: &[u8; 32]) -> Result<()> {
        #[cfg(windows)]
        {
            use windows::Win32::Storage::FileSystem::WriteFile;

            // Pipe is in byte mode — loop to handle partial writes.
            let data: &[u8] = token.as_slice();
            let mut offset = 0usize;
            while offset < data.len() {
                let mut written: u32 = 0;
                unsafe {
                    WriteFile(self.handle, Some(&data[offset..]), Some(&mut written), None)?;
                }
                if written == 0 {
                    return Err(anyhow::anyhow!(
                        "WriteFile returned 0 bytes written for token on client {}",
                        self.client_id
                    ));
                }
                offset += written as usize;
            }
            Ok(())
        }

        #[cfg(not(windows))]
        {
            let _ = token;
            Ok(())
        }
    }

    /// Send a command without waiting for response (fire-and-forget).
    ///
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    pub fn send_async(&self, cmd: &Command) -> Result<()> {
        #[cfg(windows)]
        {
            use windows::Win32::Storage::FileSystem::WriteFile;

            let data = protocol::encode(&IpcCommand::new(cmd.clone()))
                .map_err(|e| anyhow::anyhow!("failed to encode command: {e}"))?;

            // Pipe is in byte mode — loop to handle partial writes.
            let mut offset = 0usize;
            while offset < data.len() {
                let mut written: u32 = 0;
                unsafe {
                    WriteFile(self.handle, Some(&data[offset..]), Some(&mut written), None)?;
                }
                if written == 0 {
                    return Err(anyhow::anyhow!(
                        "WriteFile returned 0 bytes written for client {}",
                        self.client_id
                    ));
                }
                offset += written as usize;
            }
            Ok(())
        }

        #[cfg(not(windows))]
        {
            let _ = (self.client_id, cmd);
            Ok(())
        }
    }
}

impl Drop for CommandPipe {
    fn drop(&mut self) {
        #[cfg(windows)]
        {
            use windows::Win32::Foundation::CloseHandle;
            unsafe {
                let _ = CloseHandle(self.handle);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    #[cfg(not(windows))]
    mod non_windows {
        use super::super::*;

        const STUB_TOKEN_BYTE: u8 = 0xAB;
        const STUB_TOKEN_SIZE: usize = 32;

        #[test]
        fn connect_keeps_client_id_and_returns_stub_response() {
            let pipe = CommandPipe::connect(77, 123).unwrap();

            assert_eq!(pipe.client_id, 77);

            let (response, correlation_id) =
                pipe.send_correlated(&Command::StopMovement, 99).unwrap();

            assert_eq!(correlation_id, None);
            match response {
                Response::Error { message } => {
                    assert_eq!(message, "Not implemented (non-Windows stub)");
                }
                other => panic!("expected stub error response, got {other:?}"),
            }
        }

        #[test]
        fn send_reports_correlation_mismatch_against_stub_response() {
            let pipe = CommandPipe::connect(88, 456).unwrap();

            let err = pipe.send(&Command::StopMovement).unwrap_err();
            let msg = format!("{err:#}");

            assert!(msg.contains("response correlation mismatch"));
            assert!(msg.contains("client 88"));
            assert!(msg.contains("sent 1"));
            assert!(msg.contains("received None"));
        }

        #[test]
        fn send_advances_correlation_ids_between_calls() {
            let pipe = CommandPipe::connect(91, 789).unwrap();

            let first_err_msg = format!("{:#}", pipe.send(&Command::StopMovement).unwrap_err());
            let second_err_msg = format!("{:#}", pipe.send(&Command::StopMovement).unwrap_err());

            assert!(first_err_msg.contains("sent 1"));
            assert!(second_err_msg.contains("sent 2"));
        }

        #[test]
        fn send_async_and_send_raw_token_are_noops_on_stub() {
            let pipe = CommandPipe::connect(55, 42).unwrap();

            assert!(pipe.send_async(&Command::StopMovement).is_ok());
            assert!(
                pipe.send_raw_token(&[STUB_TOKEN_BYTE; STUB_TOKEN_SIZE])
                    .is_ok()
            );
        }
    }
}
