//! Named pipe CLIENT (orchestrator side).
//!
//! Connects to a named pipe created by the injected DLL and sends commands,
//! optionally waiting for a response. On non-Windows platforms this is a
//! compile-only stub.

use anyhow::Result;
use textquest_common::ipc::{Command, Response};
#[cfg(windows)]
use textquest_common::protocol;
use textquest_common::types::ClientId;

/// Sends commands to an injected DLL via named pipe.
pub struct CommandPipe {
    client_id: ClientId,
    #[cfg(windows)]
    handle: windows::Win32::Foundation::HANDLE,
}

impl CommandPipe {
    /// Connect to the named pipe for a specific client.
    ///
    /// Pipe name is generated by `textquest_common::ipc::pipe_name(session_id, client_id)`
    /// and includes both the session ID and the client ID for disambiguation.
    ///
    /// IMPORTANT: `client_id` must be the EQ process PID, not a sequential
    /// index. The injected DLL creates its pipe using `std::process::id()`
    /// (i.e., the PID) as the `client_id`. The orchestrator must match this
    /// by passing the PID discovered via `find_processes_by_name`.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    pub fn connect(client_id: ClientId, session_id: u64) -> Result<Self> {
        #[cfg(windows)]
        {
            use windows::Win32::Foundation::GENERIC_READ;
            use windows::Win32::Storage::FileSystem::{
                CreateFileA, FILE_ATTRIBUTE_NORMAL, OPEN_EXISTING,
            };
            use windows::core::PCSTR;

            let pipe_name = format!(
                "{}\0",
                textquest_common::ipc::pipe_name(session_id, client_id)
            );

            let handle = unsafe {
                CreateFileA(
                    PCSTR(pipe_name.as_ptr()),
                    GENERIC_READ.0 | windows::Win32::Foundation::GENERIC_WRITE.0,
                    windows::Win32::Storage::FileSystem::FILE_SHARE_NONE,
                    None,
                    OPEN_EXISTING,
                    FILE_ATTRIBUTE_NORMAL,
                    None,
                )
            }?;

            Ok(Self { client_id, handle })
        }

        #[cfg(not(windows))]
        {
            let _ = session_id;
            Ok(Self { client_id })
        }
    }

    /// Send a command and wait for response.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    pub fn send(&self, cmd: &Command) -> Result<Response> {
        #[cfg(windows)]
        {
            use windows::Win32::Storage::FileSystem::{ReadFile, WriteFile};

            let data = protocol::encode(cmd)
                .map_err(|e| anyhow::anyhow!("failed to encode command: {e}"))?;

            // Pipe is in byte mode (PIPE_TYPE_BYTE), so partial writes are
            // possible. Loop until all bytes are written.
            let mut offset = 0usize;
            while offset < data.len() {
                let mut written: u32 = 0;
                unsafe {
                    WriteFile(self.handle, Some(&data[offset..]), Some(&mut written), None)?;
                }
                if written == 0 {
                    return Err(anyhow::anyhow!(
                        "WriteFile returned 0 bytes written for client {}",
                        self.client_id
                    ));
                }
                offset += written as usize;
            }

            // Read response (buffer sized to MAX_MESSAGE_SIZE + length prefix)
            let mut buf = vec![0u8; protocol::MAX_MESSAGE_SIZE as usize + 4];
            let mut bytes_read: u32 = 0;
            unsafe {
                ReadFile(self.handle, Some(&mut buf), Some(&mut bytes_read), None)?;
            }

            let (response, _) = protocol::decode::<Response>(&buf[..bytes_read as usize])
                .ok_or_else(|| {
                    anyhow::anyhow!("Failed to decode response from client {}", self.client_id)
                })?;

            Ok(response)
        }

        #[cfg(not(windows))]
        {
            let _ = (self.client_id, cmd);
            Ok(Response::Error {
                message: "Not implemented (non-Windows stub)".into(),
            })
        }
    }

    /// Send the raw 32-byte session token for authentication handshake.
    /// Must be called once after connecting, before sending any commands.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    pub fn send_raw_token(&self, token: &[u8; 32]) -> Result<()> {
        #[cfg(windows)]
        {
            use windows::Win32::Storage::FileSystem::WriteFile;

            // Pipe is in byte mode — loop to handle partial writes.
            let data: &[u8] = token.as_slice();
            let mut offset = 0usize;
            while offset < data.len() {
                let mut written: u32 = 0;
                unsafe {
                    WriteFile(self.handle, Some(&data[offset..]), Some(&mut written), None)?;
                }
                if written == 0 {
                    return Err(anyhow::anyhow!(
                        "WriteFile returned 0 bytes written for token on client {}",
                        self.client_id
                    ));
                }
                offset += written as usize;
            }
            Ok(())
        }

        #[cfg(not(windows))]
        {
            let _ = token;
            Ok(())
        }
    }

    /// Send a command without waiting for response (fire-and-forget).
    ///
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    pub fn send_async(&self, cmd: &Command) -> Result<()> {
        #[cfg(windows)]
        {
            use windows::Win32::Storage::FileSystem::WriteFile;

            let data = protocol::encode(cmd)
                .map_err(|e| anyhow::anyhow!("failed to encode command: {e}"))?;

            // Pipe is in byte mode — loop to handle partial writes.
            let mut offset = 0usize;
            while offset < data.len() {
                let mut written: u32 = 0;
                unsafe {
                    WriteFile(self.handle, Some(&data[offset..]), Some(&mut written), None)?;
                }
                if written == 0 {
                    return Err(anyhow::anyhow!(
                        "WriteFile returned 0 bytes written for client {}",
                        self.client_id
                    ));
                }
                offset += written as usize;
            }
            Ok(())
        }

        #[cfg(not(windows))]
        {
            let _ = (self.client_id, cmd);
            Ok(())
        }
    }
}

impl Drop for CommandPipe {
    fn drop(&mut self) {
        #[cfg(windows)]
        {
            use windows::Win32::Foundation::CloseHandle;
            unsafe {
                let _ = CloseHandle(self.handle);
            }
        }
    }
}
