pub mod fallback;
pub mod priority_queue;

use anyhow::Result;
use dmft_common::soul::{MoodState, PersonalityTraits, SpeechStyle};

/// Priority level for LLM requests. Higher priority = processed first.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum LlmPriority {
    /// Idle chatter, ambient flavor text
    Low = 0,
    /// Game events, combat reactions
    Medium = 1,
    /// Real player interaction — always highest priority
    High = 2,
}

/// Situation context for the LLM to generate an appropriate response.
#[derive(Debug, Clone)]
pub enum Situation {
    /// Responding to a real player's tell/say
    PlayerChat {
        player_name: String,
        message: String,
        channel: String,
    },
    /// Reacting to a game event
    GameEvent { description: String },
    /// Idle chatter / flavor text
    IdleChatter,
    /// Reacting to another bot character
    BotChat {
        character_name: String,
        message: String,
    },
    /// Combat reaction (kill, death, loot)
    CombatReaction { description: String },
}

/// Request to generate text via LLM or fallback.
#[derive(Debug, Clone)]
pub struct LlmRequest {
    pub character_name: String,
    pub traits: PersonalityTraits,
    pub mood: MoodState,
    pub speech_style: SpeechStyle,
    pub situation: Situation,
    pub priority: LlmPriority,
    /// Recent memory context (serialized snippets for LLM prompt building)
    pub memory_context: Vec<String>,
    /// Backstory snippet for this character
    pub backstory: String,
}

/// Response from an LLM provider (or fallback).
#[derive(Debug, Clone)]
pub struct LlmResponse {
    pub text: String,
    /// Whether this was generated by a real LLM or the trait-based fallback
    pub from_llm: bool,
    /// Tokens used (0 for fallback)
    pub tokens_used: u32,
}

/// Trait for LLM providers. Sync in Phase 1 (no async runtime).
/// Implementations: TraitDrivenResponder (fallback), future Gemini/Claude API clients.
pub trait LlmProvider {
    /// Generate a response for the given request.
    /// Returns Ok(response) or Err if generation fails entirely.
    fn generate(&mut self, request: &LlmRequest) -> Result<LlmResponse>;

    /// Provider name for logging/diagnostics.
    fn name(&self) -> &str;

    /// Whether this provider is currently available (API key set, quota remaining, etc.)
    fn is_available(&self) -> bool;
}

#[cfg(test)]
mod tests {
    use super::*;
    use dmft_common::soul::{MoodState, PersonalityTraits, SpeechStyle};

    #[test]
    fn llm_priority_ordering() {
        assert!(LlmPriority::Low < LlmPriority::Medium);
        assert!(LlmPriority::Medium < LlmPriority::High);
        assert!(LlmPriority::Low < LlmPriority::High);
    }

    #[test]
    fn llm_priority_equality() {
        assert_eq!(LlmPriority::Low, LlmPriority::Low);
        assert_ne!(LlmPriority::Low, LlmPriority::High);
    }

    #[test]
    fn llm_priority_copy_clone() {
        let p = LlmPriority::Medium;
        let c = p; // Copy
        assert_eq!(p, c);
        let cl = p.clone();
        assert_eq!(p, cl);
    }

    #[test]
    fn llm_priority_debug() {
        assert_eq!(format!("{:?}", LlmPriority::Low), "Low");
        assert_eq!(format!("{:?}", LlmPriority::Medium), "Medium");
        assert_eq!(format!("{:?}", LlmPriority::High), "High");
    }

    #[test]
    fn situation_variants_debug_and_clone() {
        let situations = [
            Situation::PlayerChat {
                player_name: "Dave".into(),
                message: "Hello".into(),
                channel: "say".into(),
            },
            Situation::GameEvent {
                description: "ding".into(),
            },
            Situation::IdleChatter,
            Situation::BotChat {
                character_name: "Grimjaw".into(),
                message: "Hey".into(),
            },
            Situation::CombatReaction {
                description: "killed orc".into(),
            },
        ];
        for s in &situations {
            let _ = format!("{:?}", s);
            let _ = s.clone();
        }
    }

    #[test]
    fn llm_request_construction() {
        let req = LlmRequest {
            character_name: "TestChar".into(),
            traits: PersonalityTraits::default(),
            mood: MoodState::Neutral,
            speech_style: SpeechStyle::default(),
            situation: Situation::IdleChatter,
            priority: LlmPriority::Low,
            memory_context: vec!["memory1".into()],
            backstory: "A brave warrior".into(),
        };
        assert_eq!(req.character_name, "TestChar");
        assert_eq!(req.priority, LlmPriority::Low);
        assert_eq!(req.memory_context.len(), 1);
        let _ = format!("{:?}", req);
    }

    #[test]
    fn llm_response_construction() {
        let resp = LlmResponse {
            text: "Hail, traveler!".into(),
            from_llm: false,
            tokens_used: 0,
        };
        assert!(!resp.from_llm);
        assert_eq!(resp.tokens_used, 0);
        let cloned = resp.clone();
        assert_eq!(cloned.text, "Hail, traveler!");
        let _ = format!("{:?}", cloned);
    }

    #[test]
    fn llm_response_from_real_llm() {
        let resp = LlmResponse {
            text: "Generated text".into(),
            from_llm: true,
            tokens_used: 150,
        };
        assert!(resp.from_llm);
        assert_eq!(resp.tokens_used, 150);
    }

    #[test]
    fn llm_request_clone() {
        let req = LlmRequest {
            character_name: "Test".into(),
            traits: PersonalityTraits::default(),
            mood: MoodState::Happy,
            speech_style: SpeechStyle::default(),
            situation: Situation::IdleChatter,
            priority: LlmPriority::High,
            memory_context: vec![],
            backstory: String::new(),
        };
        let cloned = req.clone();
        assert_eq!(cloned.character_name, "Test");
        assert_eq!(cloned.priority, LlmPriority::High);
    }
}
