/// Trait-based fallback responder — generates text without an LLM API.
pub mod fallback;
/// Priority queue for LLM requests — ensures high-priority requests are processed first.
pub mod priority_queue;

use anyhow::Result;
use dmft_common::soul::{MoodState, PersonalityTraits, SpeechStyle};

/// Priority level for LLM requests. Higher priority = processed first.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum LlmPriority {
    /// Idle chatter, ambient flavor text
    Low = 0,
    /// Game events, combat reactions
    Medium = 1,
    /// Real player interaction — always highest priority
    High = 2,
}

/// Situation context for the LLM to generate an appropriate response.
#[derive(Debug, Clone)]
pub enum Situation {
    /// Responding to a real player's tell/say
    PlayerChat {
        /// Name of the player who sent the message.
        player_name: String,
        /// The message text.
        message: String,
        /// Chat channel (say, tell, group, etc.).
        channel: String,
    },
    /// Reacting to a game event
    GameEvent {
        /// Human-readable description of the game event.
        description: String,
    },
    /// Idle chatter / flavor text
    IdleChatter,
    /// Reacting to another bot character
    BotChat {
        /// Name of the bot character who sent the message.
        character_name: String,
        /// The message text.
        message: String,
    },
    /// Combat reaction (kill, death, loot)
    CombatReaction {
        /// Description of the combat event (kill, death, loot).
        description: String,
    },
}

/// Request to generate text via LLM or fallback.
#[derive(Debug, Clone)]
pub struct LlmRequest {
    /// Character name for prompt context.
    pub character_name: String,
    /// Personality trait vector (openness, conscientiousness, etc.).
    pub traits: PersonalityTraits,
    /// Current emotional state.
    pub mood: MoodState,
    /// How this character speaks (formal, casual, etc.).
    pub speech_style: SpeechStyle,
    /// What triggered this request.
    pub situation: Situation,
    /// Processing priority.
    pub priority: LlmPriority,
    /// Recent memory context (serialized snippets for LLM prompt building)
    pub memory_context: Vec<String>,
    /// Backstory snippet for this character
    pub backstory: String,
}

/// Response from an LLM provider (or fallback).
#[derive(Debug, Clone)]
pub struct LlmResponse {
    /// Generated text to speak or emote.
    pub text: String,
    /// Whether this was generated by a real LLM or the trait-based fallback
    pub from_llm: bool,
    /// Tokens used (0 for fallback)
    pub tokens_used: u32,
}

/// Trait for LLM providers. Sync in Phase 1 (no async runtime).
/// Implementations: `TraitDrivenResponder` (fallback), future Gemini/Claude API clients.
pub trait LlmProvider {
    /// Generate a response for the given request.
    /// Returns Ok(response) or Err if generation fails entirely.
    ///
    /// # Errors
    ///
    /// Returns an error if the operation fails.
    fn generate(&mut self, request: &LlmRequest) -> Result<LlmResponse>;

    /// Provider name for logging/diagnostics.
    fn name(&self) -> &str;

    /// Whether this provider is currently available (API key set, quota remaining, etc.)
    fn is_available(&self) -> bool;
}
