name: Auto Branch Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  delete_branch:
    name: Delete branch after merge
    runs-on: [self-hosted, Linux, X64, textquest]
    if: github.event.pull_request.merged == true
    steps:
      - name: Delete merged branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ github.token }}
          branches: ${{ github.event.pull_request.head.ref }}
          delete_orphaned_branches: false
